import { IconNames } from '@blueprintjs/icons';

import { ICONS } from '../../../../constants/icons';

export const APPROVAL_METHODS = {
  SPONSOR: IconNames.FULL_CIRCLE,
  SOLID_CIRCLE: IconNames.FULL_CIRCLE,
  AUDIT: ICONS.TICK,
  SUBMIT: ICONS.TICK,
  TICK: ICONS.TICK,
  COUNTERSIGN: IconNames.CIRCLE,
  HOLLOW_CIRCLE: ICONS.HOLLOW_CIRCLE,
  OPTIONAL_COUNTERSIGN: IconNames.SELECTION,
  DOUBLE_CIRCLE: '',
  FILE_RECORD: IconNames.STAR_EMPTY,
  HOLLOW_STAR: ICONS.HOLLOW_STAR,
  REVIEW_RECORD: IconNames.STAR,
  SOLID_STAR: '',
  SECOND_INSTANCE: ICONS.SECOND_INSTANCE,
  SOLID_TRIANGLE: ICONS.SECOND_INSTANCE,
  AUDIT_ONE: ICONS.TICK_ONE,
  TICK_ONE: ICONS.TICK_ONE,
  AUDIT_TWO: ICONS.TICK_TWO,
  TICK_TWO: ICONS.TICK_TWO,
  AUDIT_THREE: ICONS.TICK_THREE,
  TICK_THREE: ICONS.TICK_THREE,
  HOLLOW_TRIANGLE: ICONS.HOLLOW_TRIANGLE,
  AUDIT_OPTIONAL: ICONS.AUDIT_OPTIONAL,
  TICK_OPTIONAL: ICONS.AUDIT_OPTIONAL,
  HOLLOW_CIRCLE_ON_DEMAND: ICONS.HOLLOW_CIRCLE_ON_DEMAND,
  TICK_ON_DEMAND: ICONS.TICK_ON_DEMAND,
  DOUBLE_CIRCLE_ON_DEMAND: '',
  SOLID_STAR_ON_DEMAND: '',
};

export const ON_DEMAND_ICON = {
  TICK_ON_DEMAND: 'TICK_ON_DEMAND',
  HOLLOW_CIRCLE_ON_DEMAND: 'HOLLOW_CIRCLE_ON_DEMAND',
  DOUBLE_CIRCLE_ON_DEMAND: 'DOUBLE_CIRCLE_ON_DEMAND',
  SOLID_STAR_ON_DEMAND: 'SOLID_STAR_ON_DEMAND',
  HOLLOW_STAR_ON_DEMAND: 'HOLLOW_STAR_ON_DEMAND',
};

export const SPECIAL_ICON = {
  AUDIT_OPTIONAL: 'AUDIT_OPTIONAL',
  TICK_OPTIONAL: 'TICK_OPTIONAL',
};
